Multiscale Vision Transformers
SforAiDl/vformer pull request #40
Opened 2021-11-28 06:19 UTC by Amapocho

#14

2021-11-28 06:48 UTC, abhi-glitchhg requested changes
Could you please use Feedforward class from `encoder/nn` as MLP Instead of 'common/mlp'?

Also you can import DropPath from timm library, use this import statement - `from timm.models.layers import DropPath`, 

Also if Pull Resquest is still in progress, you can change it to Draft.

2021-11-28 07:14 UTC, Amapocho commented
> Could you please use Feedforward class from `encoder/nn` as MLP Instead of 'common/mlp'?
> 
> Also you can import DropPath from timm library, use this import statement - `from timm.models.layers import DropPath`,
> 
> Also if Pull Resquest is still in progress, you can change it to Draft.

Made the necessary changes

2022-01-14 07:32 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +
I would suggest to use relative imports

2022-01-14 07:33 UTC, abhi-glitchhg commented on vformer/encoder/multiscale.py
> +
```suggestion
from ..attention import MultiScaleAttention
from ..utils import ENCODER_REGISTRY

@ENCODER_REGISTRY.register()
```

2022-01-14 07:33 UTC, abhi-glitchhg commented on vformer/attention/multiscale.py
> +class MultiScaleAttention(nn.Module):
```suggestion
@ATTENTION_REGISTRY.register()
class MultiScaleAttention(nn.Module):
```

2022-01-14 19:32 UTC, abhi-glitchhg commented on vformer/encoder/embedding/patch_multiscale.py
> +class PatchEmbed(nn.Module):
```suggestion
import torch.nn as nn

class PatchEmbed(nn.Module):
```

2022-01-14 19:32 UTC, abhi-glitchhg commented on vformer/encoder/multiscale.py
> +        x_res, _ = attention_pool(
here You need to import attention_pool  from the embedding module.

2022-01-14 19:32 UTC, abhi-glitchhg commented on tests/test_attention.py
> +    thw  = [2,2,2]
I did one more review round; 
i guess you will need to create 5 dimensional input tensors (Batch,Channels,Time,Height,width) according to the authors code

2022-01-16 19:59 UTC, abhi-glitchhg requested changes

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +             POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
```suggestion
             patch_kernel = (3, 7, 7),
             patch_padding = (1, 3, 3),
             DIM_MUL=[[1, 2.0], [3, 2.0], [14, 2.0]],
             HEAD_MUL= [[1, 2.0], [3, 2.0], [14, 2.0]],
             POOL_KVQ_KERNEL= [3, 3, 3],
             POOL_KV_STRIDE_ADAPTIVE=[1, 8, 8],
             POOL_Q_STRIDE= [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]],
```

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +             depth = 16
```suggestion
             num_classes = 400,
             embed_dim = 96,
             num_heads = 1,
             mlp_ratio = 4.0,
             qkv_bias = True,
             drop_rate = 0.0,
             depth = 16,
```

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +
```suggestion
import torch.nn as nn
from functools import partial
```

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +                pool_q[POOL_Q_STRIDE[i][0]] = POOL_KVQ_KERNEL
```suggestion
            ]
            if POOL_KVQ_KERNEL is not None:
                pool_q[POOL_Q_STRIDE[i][0]] = POOL_KVQ_KERNEL
```

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +                ] = KVQ_KERNEL
`KVQ_KERNEL`  this variable is not defined .

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +                attention_block = checkpoint_wrapper(attention_block)
```suggestion
            )
            if ACT_CHECKPOINT:
                attention_block = checkpoint_wrapper(attention_block)
```

2022-01-16 19:59 UTC, abhi-glitchhg commented on vformer/models/classification/multiscale.py
> +        )
```suggestion
            num_classes,
            dropout_rate=self.drop_rate,
            act_func=HEAD_ACT,
        )
```

2022-07-03 15:35 UTC, closed without merging