* Enhanced docstring
SforAiDl/vformer pull request #49
Opened 2021-12-25 17:26 UTC by abhi-glitchhg

During the last PR, I had to revert back  to meet the compatibility issue

In this PR I have added some docstrings and Minor changes like changing variable names

this PR is the same as - #48 with edited title :) 

@NeelayS

2021-12-25 17:38 UTC, NeelayS commented on vformer/attention/spatial.py
> +        Args:
We are following NumPy-style, so this needs to be the following way, doesn't it?

```suggestion
        Parameters
        --------------
```

2021-12-25 17:39 UTC, NeelayS commented on vformer/attention/spatial.py
> +        Returns: torch.Tensor
```suggestion
        Returns
        ----------
        
        torch.Tensor
```

2021-12-25 17:39 UTC, NeelayS requested changes
Left a comment.

2021-12-25 17:41 UTC, NeelayS commented
Also, you can edit the name of a PR after opening it by clicking the edit button besides it.

2021-12-25 18:25 UTC, abhi-glitchhg commented
> 

F, sorry :/

2021-12-26 12:30 UTC, NeelayS requested changes
Have added a few suggestions. Please check.

2021-12-26 12:30 UTC, NeelayS commented on vformer/attention/spatial.py
> +            Returns output tensor by applying spatial attention on input tensor
```suggestion
                Returns output tensor by applying spatial attention on input tensor
```

2021-12-26 12:30 UTC, NeelayS commented on vformer/attention/spatial.py
> +            x: torch.Tensor
The parameter names listed can start in the same column as the Parameters heading. They don't need to be indented.

2021-12-26 12:30 UTC, NeelayS commented on vformer/attention/spatial.py
> +            x: torch.Tensor
```suggestion
        x: torch.Tensor
```

2021-12-26 12:30 UTC, NeelayS commented on vformer/attention/window.py
> +                for more understanding you may refer (this)[https://github.com/microsoft/Swin-Transformer/issues/38]
For this link to render properly in the documentation, you will have to use the RST format of specifying links.

2021-12-26 12:30 UTC, NeelayS commented on vformer/encoder/pyramid.py
> +        Kwargs
You don't need to have a separate section for **kwargs. Check [this](https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#:~:text=length%20argument%20list.-,**kwargs,-Arbitrary%20keyword%20arguments)

2021-12-28 09:48 UTC, NeelayS commented
@abhi-glitchhg

2021-12-30 17:22 UTC, closed without merging