Convit
SforAiDl/vformer pull request #63
Opened 2022-01-21 06:13 UTC by aditya-agrawal-30502

2022-01-21 06:13 UTC, aditya-agrawal-30502 commented
#30

2022-01-24 18:05 UTC, NeelayS requested changes

2022-01-24 18:05 UTC, NeelayS commented on vformer/attention/__init__.py
> +from .gatedpositional import GatedPositionalSelfAttention
Could you please change the file name to `gated_positional.py`?

2022-01-24 18:05 UTC, NeelayS commented on vformer/attention/gatedpositional.py
> +        l = int(n ** 0.5)
```suggestion

        l = int(n ** 0.5)
```

2022-01-24 18:05 UTC, NeelayS commented on vformer/encoder/conv.py
> +        for _ in range(depth):
```suggestion

        for _ in range(depth):
```

2022-01-24 18:05 UTC, NeelayS commented on vformer/models/classification/__init__.py
> +from .conv import ConViT
Could you please change the name of the file to `convit.py`?

2022-01-24 18:05 UTC, NeelayS commented on vformer/models/classification/conv.py
> +from ...encoder import ConvitEncoder
```suggestion
from ...encoder import ConViTEncoder
```

2022-01-24 18:05 UTC, NeelayS commented on vformer/models/classification/conv.py
> +        self.encoder_gpsa = ConvitEncoder(
```suggestion 

        self.encoder_gpsa = ConViTEncoder(
```

2022-01-24 18:05 UTC, NeelayS commented on vformer/encoder/__init__.py
> +from .conv import ConvitEncoder
Could you please change the name of the file to `convit.py`?

2022-01-25 16:38 UTC, merged