Model3 of ViViT
SforAiDl/vformer pull request #66
Opened 2022-02-05 08:24 UTC by abhi-glitchhg

Here is a model3 of ViViT

cc @NeelayS @aditya-agrawal-30502

2022-02-05 10:05 UTC, abhi-glitchhg commented on vformer/encoder/vivit.py
> +
I forgot to add layer norm in these; will update this

2022-02-05 10:05 UTC, abhi-glitchhg reviewed
.

2022-02-08 12:20 UTC, NeelayS requested changes

2022-02-08 12:20 UTC, NeelayS commented on tests/test_encoder.py
> +    encoder = ENCODER_REGISTRY.get("ViViTEncoder")(
```suggestion

    encoder = ENCODER_REGISTRY.get("ViViTEncoder")(
```

2022-02-08 12:20 UTC, NeelayS commented on tests/test_encoder.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on tests/test_encoder.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on tests/test_models.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on tests/test_models.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/models/classification/vivit.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/models/classification/vivit.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/models/classification/vivit.py
> +
```suggestion
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/models/classification/vivit.py
> +        return x
```suggestion

        return x
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/encoder/vivit.py
> +        return x
```suggestion

        return x
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/encoder/vivit.py
> +        b = x.shape[0]
```suggestion

        b = x.shape[0]
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/encoder/vivit.py
> +        for blk in self.encoder:
```suggestion

        for blk in self.encoder:
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/encoder/vivit.py
> +        x = x.reshape(b, -1, x.shape[-1])
```suggestion

        x = x.reshape(b, -1, x.shape[-1])
```

2022-02-08 12:20 UTC, NeelayS commented on vformer/encoder/vivit.py
> +        b, n, s, d = x.shape
```suggestion

        b, n, s, d = x.shape
```

2022-02-08 12:37 UTC, merged